name: CI

on:
  pull_request:
  push:
  schedule:
    - cron: "0 5 * * 6"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        mruby_version:
          - "3.0.0"
          - "3.1.0"
          - "3.2.0"
          - "3.3.0"
          - "3.4.0"
          - "4.0.0"
          - "master"
        regexp_lib:
          - "pcre"
          - "onig"
        exclude:
          - mruby_version: "4.0.0"
            regexp_lib: "pcre"
        include:
          - mruby_version: "master"
            regexp_lib: "native"
    name: mruby ${{ matrix.mruby_version }} - ${{ matrix.regexp_lib }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.mruby_version == 'master' || matrix.regexp_lib == 'onig' }}
    steps:
      - uses: actions/checkout@v6
      - name: Clone mruby ${{ matrix.mruby_version }}
        uses: actions/checkout@v6
        with:
          repository: mruby/mruby
          ref: ${{ matrix.mruby_version }}
          path: mruby
      - name: Build & test
        env:
          CC: gcc
          MRUBY_CONFIG: ${{ github.workspace }}/.ci_build_config.rb
          REGEXP_LIB: ${{ matrix.regexp_lib }}
        run: |
          cd mruby
          rake test
